
service: using-multiple-stages

# Step 3. In this_file, add a `custom` block and define a `stage` property. Set that property to a serverless `${variable, defaultValue}` with a default value of 'dev' #
custom:
  stage: ${opt:stage, 'dev'} # command line option: --stage prod

provider:
  name: aws
  runtime: nodejs6.10
  # Step 4. In this_file, set the stage key to the custom.stage value set in previous step
  # Step 5. In this_file, set an environment variable that uses the serverless file variable syntax to grab a file name with the current stage in it. Example `config.dev.json`. Hint this uses nested variables http://bit.ly/2AHvkKO
  stage: ${self:custom.stage}
  environment:
    MY_STAGE_SPECIFIC_VAR: ${file(./config.${self:custom.stage}.json):projectName}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
