
service: using-env-variables-example

# Step 1. In this_file, add an environment key & value to the `provider` section. This will allow all functions in the secret to access the value. http://bit.ly/2yVp4CR #
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MY_ENV_VAR: 'hard-code'

functions:
  foo:
    handler: handler.foo
    events:
      - http:
          path: foo
          method: get
  # Step 2. In this_file, add an environment variable to the `bar` function. Adding `enviroment` to the function level scope them to a single function. http://bit.ly/2yVp4CR #
  bar:
    handler: handler.bar
    environment:
      MY_ENV_VAR_FOR_BAR: 'harco-code bar'
    events:
      - http:
          path: bar
          method: get

# Step 5. After adding your environment variables to serverless.yml and handler.js.
# Run `sls deploy` to deploy the service #
